In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../datasets/flights_7.csv')
df.head()

C:\Users\tccox\AppData\Local\Temp\ipykernel_12752\2222082028.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../datasets/flights_7.csv')

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,...,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DATE,SCHEDULED_DEPARTURE_TS,ACTUAL_DEPARTURE_TS,SCHEDULED_ARRIVAL_TS,ACTUAL_ARRIVAL_TS
0,1,1,4,AA,LAX,PBI,00:10,00:02,-8.0,12.0,...,737.0,4.0,07:50,07:41,-9.0,2015-01-01,2015-01-01 00:10:00,2015-01-01 00:02:00,2015-01-01 07:50:00,2015-01-01 07:41:00
1,1,1,4,US,SFO,CLT,00:20,00:18,-2.0,16.0,...,800.0,11.0,08:06,08:11,5.0,2015-01-01,2015-01-01 00:20:00,2015-01-01 00:18:00,2015-01-01 08:06:00,2015-01-01 08:11:00
2,1,1,4,AA,LAX,MIA,00:20,00:15,-5.0,15.0,...,748.0,8.0,08:05,07:56,-9.0,2015-01-01,2015-01-01 00:20:00,2015-01-01 00:15:00,2015-01-01 08:05:00,2015-01-01 07:56:00
3,1,1,4,AS,SEA,ANC,00:25,00:24,-1.0,11.0,...,254.0,5.0,03:20,02:59,-21.0,2015-01-01,2015-01-01 00:25:00,2015-01-01 00:24:00,2015-01-01 03:20:00,2015-01-01 02:59:00
4,1,1,4,DL,SFO,MSP,00:25,00:20,-5.0,18.0,...,604.0,6.0,06:02,06:10,8.0,2015-01-01,2015-01-01 00:25:00,2015-01-01 00:20:00,2015-01-01 06:02:00,2015-01-01 06:10:00

In [9]:
df_2 =pd.read_csv('../datasets/kaggle/flights.csv')
df_2.head()

C:\Users\tccox\AppData\Local\Temp\ipykernel_12752\4260471548.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2 =pd.read_csv('../datasets/kaggle/flights.csv')

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#list all unique numeric values in the column
values = df_2['ORIGIN_AIRPORT'].unique()
#print leng of df_2
print(len(df_2))
#if value is numeric, count
count = 0
numeric_values = []
for value in values:
    if isinstance(value, (int, float)):
        count += 1
        numeric_values.append(value)
#print length of unique values
print('{} out of {} values are numeric'.format(count, len(values)))
#remove all numeric values from the list
for value in numeric_values:
    values = values[values != value]
#only keep values that are not numeric
df_2 = df_2[df_2['ORIGIN_AIRPORT'].isin(values)]
#print length of df_2
print(len(df_2))

5819079
306 out of 930 values are numeric
5360327

In [12]:
df.columns

Index(['MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'ORIGIN_AIRPORT',
       'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME',
       'DEPARTURE_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'SCHEDULED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'WHEELS_ON', 'TAXI_IN',
       'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY', 'DATE',
       'SCHEDULED_DEPARTURE_TS', 'ACTUAL_DEPARTURE_TS', 'SCHEDULED_ARRIVAL_TS',
       'ACTUAL_ARRIVAL_TS'],
      dtype='object')

In [ ]:
#

In [6]:
#print the unique values of ORIGIN_AIRPORT and DESTINATION_AIRPORT
print(df_2['ORIGIN_AIRPORT'].unique())
print(df_2['DESTINATION_AIRPORT'].unique())
print(len(df_2['ORIGIN_AIRPORT'].unique()))

['ANC' 'LAX' 'SFO' 'SEA' 'LAS' 'DEN' 'SLC' 'PDX' 'FAI' 'MSP' 'PHX' 'SJU'
 'PBG' 'IAG' 'PSE' 'BQN' 'ORD' 'GEG' 'HNL' 'ONT' 'MCO' 'BOS' 'HIB' 'ABR'
 'MAF' 'DFW' 'MKE' 'IAH' 'BNA' 'BRO' 'VPS' 'BOI' 'BJI' 'SGF' 'PHL' 'SBN'
 'RDD' 'EUG' 'IAD' 'BUF' 'PWM' 'JFK' 'CRP' 'PIA' 'FAT' 'SMF' 'AUS' 'MCI'
 'ATL' 'JAX' 'MFR' 'IDA' 'MSN' 'DCA' 'SAT' 'CHS' 'SBA' 'SMX' 'IND' 'CLE'
 'GSP' 'BDL' 'ABI' 'RIC' 'BFL' 'OMA' 'RDM' 'FLL' 'CID' 'TPA' 'SYR' 'ROC'
 'TYR' 'LAN' 'XNA' 'GSO' 'EWR' 'PBI' 'RSW' 'OAK' 'PVD' 'RNO' 'PIT' 'ABQ'
 'MIA' 'BWI' 'LGA' 'TUL' 'LIT' 'MSY' 'OKC' 'ATW' 'PNS' 'MEM' 'TYS' 'MHT'
 'SAV' 'CLT' 'GRB' 'ABE' 'JAN' 'OAJ' 'FAR' 'ERI' 'LEX' 'CWA' 'MSO' 'TTN'
 'AMA' 'CLL' 'HOU' 'JLN' 'MLI' 'RDU' 'CVG' 'MHK' 'MOB' 'TLH' 'BHM' 'CAE'
 'TXK' 'ACY' 'DTW' 'RAP' 'TUS' 'EAU' 'DLH' 'FSD' 'INL' 'CMX' 'SPI' 'CLD'
 'COD' 'CMH' 'LRD' 'PSC' 'CPR' 'ACV' 'DAL' 'PAH' 'MRY' 'ESC' 'ISN' 'PSP'
 'MFE' 'STL' 'BTV' 'FSM' 'AEX' 'SPS' 'ACT' 'SJT' 'MTJ' 'GCC' 'OGG' 'SJC'
 'GUC' 'ORF' 'MOT' 'MLU' 'KOA' 'SAN' 'LAW' 'PIB' 'MGM' 'SBP' 'COS' 'LAR'
 'DRO' 'BIS' 'ITO' 'BTR' 'GRI' 'HLN' 'BZN' 'MDW' 'MDT' 'SCE' 'LIH' 'TWF'
 'BPT' 'GPT' 'STC' 'HPN' 'MLB' 'PLN' 'CIU' 'CAK' 'DSM' 'BLI' 'SHV' 'ROW'
 'FWA' 'SNA' 'ALB' 'HOB' 'LNK' 'CMI' 'COU' 'GTF' 'EKO' 'LGB' 'AVL' 'HSV'
 'SAF' 'GRR' 'SUX' 'LFT' 'HYS' 'ELP' 'DVL' 'ISP' 'BUR' 'DAB' 'DAY' 'GRK'
 'GJT' 'BMI' 'LBE' 'ASE' 'RKS' 'GUM' 'TVC' 'ALO' 'IMT' 'LCH' 'JNU' 'JAC'
 'MEI' 'DBQ' 'GCK' 'GNV' 'BRD' 'DIK' 'SDF' 'LBB' 'AVP' 'BTM' 'ELM' 'PIH'
 'ICT' 'SUN' 'LWS' 'VEL' 'STT' 'YUM' 'FLG' 'FCA' 'HDN' 'JMS' 'ROA' 'CHA'
 'EYW' 'MYR' 'CRW' 'MQT' 'CHO' 'ECP' 'EVV' 'EGE' 'MBS' 'GFK' 'TOL' 'BIL'
 'OTZ' 'KTN' 'STX' 'ILM' 'PUB' 'RHI' 'CDC' 'HRL' 'SCC' 'FNT' 'LSE' 'MMH'
 'APN' 'AGS' 'CEC' 'DHN' 'WRG' 'PHF' 'CNY' 'BRW' 'GGG' 'AZO' 'SRQ' 'ORH'
 'TRI' 'VLD' 'SIT' 'BQK' 'PSG' 'FAY' 'MKG' 'CSG' 'EWN' 'OME' 'SGU' 'RST'
 'GTR' 'BET' 'ABY' 'SWF' 'ILG' 'ADK' 'UST' 'YAK' 'CDV' 'OTH' 'ADQ' 'PPG'
 'BGM' 'BGR' 'ITH' 'ACK' 'MVY' 'WYS' 'DLG' 'AKN' 'GST' 'HYA' '14747'
 '14771' '12889' '12892' '14869' '10299' '11292' '14107' '11630' '10732'
 '14254' '10141' '10627' '11982' '12173' '13930' '14683' '12266' '11618'
 '10721' '13487' '11884' '15919' '13851' '11111' '10693' '12191' '14783'
 '15016' '14487' '10423' '15370' '11953' '13891' '15376' '11778' '11278'
 '14100' '13204' '15304' '11637' '14842' '10155' '11775' '11298' '11057'
 '13931' '10821' '14122' '11049' '10990' '10631' '13158' '14108' '13198'
 '11447' '12206' '13495' '14057' '15624' '10747' '15411' '12891' '10994'
 '13256' '10792' '14492' '12451' '13127' '10781' '14960' '12278' '14685'
 '11995' '13485' '11977' '10257' '13796' '13232' '13296' '14570' '14893'
 '14524' '12217' '10713' '10208' '10136' '11603' '14689' '11471' '11315'
 '13264' '12478' '14814' '11308' '11066' '12896' '10397' '14307' '11721'
 '11140' '10185' '13277' '11203' '13342' '11433' '11697' '12953' '10599'
 '12156' '14952' '10620' '11042' '15096' '10408' '15249' '11423' '12915'
 '12264' '12339' '10140' '13871' '14027' '13244' '11267' '11540' '14576'
 '10868' '13486' '13476' '14489' '12945' '15607' '10529' '11986' '14635'
 '13303' '10785' '15380' '11996' '10561' '10874' '13367' '10146' '10431'
 '11973' '10980' '12197' '14098' '12323' '10577' '11150' '10135' '11617'
 '13795' '13029' '11003' '11146' '11577' '15356' '11259' '10279' '14321'
 '14843' '11638' '14828' '11481' '12951' '10434' '12448' '14730' '15323'
 '14252' '11193' '10849' '14193' '14986' '11641' '12992' '13422' '11612'
 '11823' '11980' '13290' '10158' '10685' '13377' '11109' '11076' '11122'
 '11865' '14543' '14905' '11587' '14457' '12335' '12343' '12003' '10157'
 '12884' '14633' '15048' '10268' '15295' '12389' '11525' '14262' '12888'
 '12391' '11648' '14696' '12758' '13830' '10469' '15412' '10731' '14679'
 '14831' '11413' '13433' '12982' '11867' '14698' '11537' '15389' '12402'
 '11337' '13360' '13076' '14006' '10728' '15401' '13230' '12016' '11067'
 '11274' '11921' '12519' '11013' '10779' '14150' '14794' '12511' '12177'
 '12523' '14908' '12007' '14588' '13577' '13061' '15041' '14109' '10800'
 '12954' '12441' '12898' '11695' '16218' '14113' '11624' '11503' '10739'
 '14574' '14711' '12129' '15070' '14520' '13184' '11252' '12280' '13241'
 '11898' '15024' '14674' '10551' '12819' '13459' '10581' '13970' '10372'
 '10918' '14709' '12255' 11267 12266 10821 14771 11433 11982 11905 15411
 14679 14108 10397 13871 11618 14574 10423 11259 10800 11140 12191 12889
 13198 10529 10693 13232 11540 14570 14635 14831 11298 13204 11278 14100
 12892 12478 13930 15304 14107 12523 12954 11697 14057 12339 13487 14893
 11986 11292 14576 15370 12402 14908 12953 12758 15016 10721 12264 10685
 11612 13277 11057 12891 12197 11193 13495 13891 13244 14843 14747 11996
 10333 14262 11695 13342 14698 10431 15376 12451 14524 13830 13796 14122
 14960 16218 10713 11066 10208 14683 14869 14492 11638 11413 10792 10408
 14689 10980 14952 12951 15323 11884 14307 14730 14783 11603 11977 11921
 13577 13061 13851 11042 12448 12992 10874 12896 11308 12173 12206 13377
 10747 13256 13303 10185 10599 10140 15295 11898 13795 10728 10994 12391
 10299 12217 13290 12007 11109 15096 10627 13433 15249 12278 12915 11637
 13931 13485 11721 11775 13476 15841 14027 15380 12945 11315 15919 13360
 10868 14986 12982 10279 11150 13264 14193 11823 13367 10469 11423 11337
 11252 13029 14696 11049 13296 14685 13158 12323 10257 14588 11274 13344
 13933 15412 13422 11146 15991 13230 14794 11003 14828 10781 10990 10785
 10434 14457 11481 11537 10136 14814 10754 10135 10731 13127 14321 10849
 14098 10146 15607 11624 12177 10158 12884 15624 14256 11973 14842 15356
 10561 14113 15389 14489 12094 12888 13076 12129 13873 10157 11995 10631
 12441 12343 14252 11097 10732 10154 11122 11641 13486 12003 10620 10779
 12335 11076 15041 12156 12280 10926 12819 11865 12519 11778 10551 12389
 11953 12898 15024 10155 11013 10372 11587 13964 11980 11630 11648 14905
 11525 15070 11471 11111 14633 11447 11203 13241 12511 11067 10268 13184
 10141 13541 14150 15027 14109 15048 14006 10739 14520 11617 14487 11867
 14674 14543 10577 10170 11577 14709 14711 12255 10165 10918 15401 13970
 15497 12265 14254 10581 12016 11503 13459 14222 14025 13502 '15841'
 '13344' '15991' '10754' '14256' '13873' '11097' '10926' '13964' '11905'
 '15027' '13933' '10170' '10333' '14222' '14025' '13502' '15497' '12265']
['SEA' 'PBI' 'CLT' 'MIA' 'ANC' 'MSP' 'DFW' 'ATL' 'IAH' 'PDX' 'MCI' 'FLL'
 'ORD' 'HNL' 'PHX' 'EWR' 'JFK' 'MCO' 'BOS' 'BDL' 'ITO' 'SFO' 'KOA' 'OGG'
 'MYR' 'DTW' 'LIH' 'DEN' 'SJU' 'LAX' 'BWI' 'IAD' 'BQN' 'BUF' 'LGA' 'HOU'
 'SLC' 'PHL' 'SJC' 'OAK' 'LGB' 'TPA' 'DCA' 'TTN' 'BTR' 'LAS' 'RSW' 'BRD'
 'STL' 'RKS' 'MBS' 'SNA' 'MEI' 'MDW' 'SAN' 'RIC' 'AUS' 'OTZ' 'PIT' 'JAX'
 'MSY' 'ONT' 'PSP' 'BUR' 'DAL' 'CVG' 'SMF' 'RDU' 'JMS' 'BNA' 'DSM' 'MAF'
 'BOI' 'ELP' 'TUS' 'SCC' 'HPN' 'STT' 'MDT' 'RHI' 'SBP' 'MKE' 'JNU' 'CMH'
 'CLD' 'KTN' 'CAK' 'CRP' 'CLE' 'GPT' 'SHV' 'TYS' 'IND' 'LIT' 'SAT' 'SRQ'
 'TUL' 'GRK' 'PNS' 'BTV' 'CHS' 'DAY' 'OKC' 'SAV' 'XNA' 'COS' 'GJT' 'BZN'
 'PUB' 'HRL' 'HDN' 'MEM' 'GEG' 'ORH' 'SYR' 'GSO' 'VPS' 'LAW' 'ACY' 'LBB'
 'JAC' 'BIL' 'EUG' 'ASE' 'TVC' 'MTJ' 'CAE' 'PVD' 'HSV' 'CDC' 'YUM' 'ABQ'
 'TLH' 'MLI' 'AMA' 'EGE' 'MOB' 'JAN' 'FWA' 'MSN' 'BIS' 'MFR' 'APN' 'BHM'
 'OMA' 'LFT' 'GRR' 'MMH' 'CEC' 'SBA' 'RNO' 'CLL' 'LEX' 'LAN' 'DLH' 'SDF'
 'FAT' 'SPS' 'SGF' 'CID' 'FSM' 'MGM' 'MFE' 'AVP' 'SJT' 'ROA' 'LRD' 'MRY'
 'AGS' 'ROC' 'AEX' 'ISN' 'MLB' 'ORF' 'ICT' 'ECP' 'PIA' 'BPT' 'ACT' 'EYW'
 'FSD' 'MLU' 'CHA' 'WRG' 'FNT' 'DIK' 'MHK' 'CNY' 'BRW' 'GRB' 'ATW' 'SAF'
 'TYR' 'MKG' 'FLG' 'FCA' 'BTM' 'EVV' 'DRO' 'LNK' 'DBQ' 'FAR' 'OME' 'GSP'
 'GUC' 'MSO' 'TXK' 'MOT' 'RAP' 'ISP' 'PWM' 'GGG' 'SBN' 'BFL' 'MHT' 'ROW'
 'SIT' 'CMX' 'FAY' 'ILM' 'CMI' 'ALB' 'ABI' 'GTF' 'BMI' 'COU' 'HOB' 'GNV'
 'SUN' 'SPI' 'PSG' 'BRO' 'AVL' 'TOL' 'SGU' 'GCC' 'HLN' 'CPR' 'PIH' 'BET'
 'VEL' 'RDM' 'HYS' 'PSC' 'COD' 'INL' 'FAI' 'EKO' 'BJI' 'IDA' 'IMT' 'RST'
 'HIB' 'ABR' 'STC' 'ACV' 'ESC' 'CIU' 'SWF' 'DAB' 'TRI' 'AZO' 'CRW' 'STX'
 'GRI' 'CHO' 'GCK' 'PLN' 'LSE' 'SMX' 'RDD' 'PHF' 'LCH' 'GTR' 'LAR' 'ERI'
 'PAH' 'EAU' 'LBE' 'BLI' 'DVL' 'CWA' 'ILG' 'OAJ' 'ABE' 'ALO' 'ABY' 'DHN'
 'TWF' 'ADK' 'ELM' 'VLD' 'PIB' 'SUX' 'GUM' 'SCE' 'UST' 'BQK' 'JLN' 'LWS'
 'MQT' 'EWN' 'CSG' 'PBG' 'PSE' 'IAG' 'YAK' 'CDV' 'OTH' 'ADQ' 'PPG' 'GFK'
 'BGM' 'BGR' 'ITH' 'ACK' 'MVY' 'WYS' 'DLG' 'AKN' 'GST' 'HYA' '11298'
 '13487' '13303' '11057' '13930' '10693' '14747' '12266' '12478' '14057'
 '10397' '13198' '12173' '11618' '13204' '12402' '12758' '14771' '11292'
 '13830' '14107' '12982' '11697' '12519' '13577' '14869' '12339' '13232'
 '11259' '15016' '12892' '12889' '10140' '10721' '15304' '14679' '14100'
 '10732' '10821' '14831' '14843' '14570' '12191' '11433' '12264' '14893'
 '13796' '12953' '14122' '13495' '12451' '11042' '11278' '14908' '13342'
 '13891' '10299' '12523' '12954' '14520' '12129' '10713' '10431' '11066'
 '10994' '10423' '10792' '14683' '10800' '10551' '11193' '14307' '11540'
 '14635' '13851' '15376' '11884' '14492' '14027' '13970' '13184' '13296'
 '10599' '11986' '14698' '11423' '13244' '14574' '12992' '13241' '12217'
 '13871' '12197' '11003' '15919' '14524' '14689' '10529' '14576' '11995'
 '11267' '12819' '14633' '11996' '13256' '13158' '12448' '10781' '13422'
 '16218' '15370' '10868' '14730' '13931' '13485' '14986' '15024' '11823'
 '11721' '14685' '10257' '12206' '12255' '12951' '14709' '14321' '12391'
 '14794' '10874' '12278' '11638' '10372' '11122' '14457' '15096' '12896'
 '11109' '10279' '11481' '15412' '14814' '11641' '10980' '12945' '10990'
 '10157' '13076' '13230' '15295' '10918' '13933' '11953' '10135' '14262'
 '11067' '13277' '11603' '10561' '11612' '15624' '11977' '15380' '13367'
 '14193' '10333' '11778' '11140' '14783' '10136' '14842' '11049' '14696'
 '11695' '11637' '15401' '14674' '13061' '10685' '11982' '10469' '11921'
 '14108' '11413' '12891' '11905' '14960' '15411' '10155' '10747' '10728'
 '13290' '13433' '10208' '11973' '15323' '10849' '13360' '13795' '14952'
 '13377' '10408' '10627' '13344' '13476' '11775' '10158' '11898' '13029'
 '15249' '11337' '12915' '15356' '13264' '11252' '10185' '11624' '12323'
 '15841' '10785' '11146' '14098' '10434' '12389' '15991' '11315' '11150'
 '12884' '11537' '11274' '11076' '10754' '13873' 13930 10599 11697 12266
 14492 11298 14869 14683 11278 15016 13244 11433 12951 13931 11259 10423
 14893 11721 12191 14107 14122 14679 13796 11292 13232 12339 14771 14908
 13204 11540 13303 12889 13487 12953 10721 13198 11057 14100 15304 14828
 12982 14057 10136 11193 11042 12173 11618 15412 13495 15370 10397 14814
 11308 10685 11982 14747 14831 13851 12892 13296 11638 14321 11884 12992
 14027 15919 12007 13830 10731 14685 12884 10135 11996 12478 12217 13485
 11973 10792 14730 10800 11986 11481 10821 10140 10299 14842 10980 12197
 10990 12945 10781 11995 10257 13891 13158 12264 12758 10279 14588 10185
 13377 14524 10693 12206 15376 12451 11066 11603 14689 11003 11267 15607
 10994 14635 13342 14576 15096 14986 12278 12448 10146 14262 10713 14307
 15024 10157 13422 10874 14570 14843 15070 14193 13486 12003 13127 13264
 12177 12441 12523 14794 12094 12156 14113 12280 11641 14489 10849 12896
 14256 10561 12954 10620 11097 10779 11122 10631 12888 15389 15041 14252
 12343 12129 11648 10154 13577 14457 13076 12898 13029 12389 13871 10529
 12402 11637 13256 12335 11865 11775 10551 15249 10747 15624 12391 10208
 10926 12819 11423 13367 14952 13277 11980 11977 11778 15411 13964 11953
 11630 11049 11013 11587 15380 11823 11252 11111 14698 11624 13795 12915
 14108 11695 11612 10627 13360 15027 10469 14696 14574 15323 11203 14633
 11337 13241 14098 10408 10155 11146 13061 14905 13433 11471 14783 10785
 11140 12511 12323 10868 14960 10431 10268 11447 11067 13290 15048 13541
 13476 16218 11150 12891 11921 10141 14150 14006 13184 11537 10434 13230
 11617 11525 11898 11109 11867 14711 11577 12016 14520 14487 10739 14109
 10165 11413 10158 15356 14709 12255 14543 11274 15841 10577 14674 10170
 10333 10728 13970 15295 15401 15991 11905 10918 15497 10754 13344 11503
 13459 13873 11315 12519 11076 10581 12265 14254 10732 10372 13933 14222
 14025 13502 '10146' '13486' '12003' '13127' '12441' '12177' '12156'
 '14113' '14256' '14489' '10620' '11097' '10779' '10631' '12888' '15389'
 '15041' '14252' '12343' '12898' '11648' '12280' '12335' '11865' '10731'
 '10926' '11980' '11630' '11013' '11587' '11111' '13964' '15027' '11203'
 '15070' '14150' '11471' '14905' '12511' '10268' '15048' '11447' '11577'
 '10141' '11308' '11617' '11525' '11867' '12016' '10739' '14711' '14006'
 '14109' '14487' '15607' '14543' '14588' '10577' '10170' '12007' '14828'
 '14222' '13459' '13502' '14254' '14025' '15497' '12265' '10581' '10666']
930